parameters: 
  signSteps: []
  
steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: scripts/setversion.csproj
    arguments: -c $(BuildConfiguration)   
  displayName: Set Version
  condition: eq(variables['system.pullrequest.isfork'], false)

- task: VSBuild@1
  inputs:    
    solution: .\Zeroconf\Zeroconf.csproj
    configuration: $(BuildConfiguration)
    msbuildArgs: '/restore /m /t:Pack /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)\Packages'
  displayName: Build

- ${{ parameters.signSteps }}

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Packages
    artifactType: container
    artifactName: Packages
  condition: eq(variables['system.pullrequest.isfork'], false)
  