image: Visual Studio 2017

environment:
  SignClientSecret:
    secure: EvUuRb2cdsB5h7dJ49CkDDsZHHbwomGvMbcVcRsCSIp58IxVHFzAZrJSE+qpihtU
  SignClientUser:
    secure: 9nw9iBguE89m36udK51REeCIHSi5lAXmFIfS5LuAXio=
     
install: 
  - cmd: nuget install SignClient -Version 0.9.0 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion
    
build_script:
  - cmd: msbuild Zeroconf\Zeroconf.csproj /t:restore
  - cmd: msbuild Zeroconf\Zeroconf.csproj /t:pack /p:Configuration=Release 
  
after_build:
  - cmd: move Zeroconf\bin\Release\*.nupkg .
  - ps: '.\SignClient\Sign-Package.ps1'

artifacts:
  - path: '*.nupkg'
  
deploy:
  provider: NuGet
  server: https://www.myget.org/F/zeroconf/api/v2/package
  symbol_server: https://www.myget.org/F/zeroconf/symbols/api/v2/package
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/
